name: etl_daily # Name of the action that will appear in the "Actions" tab

# (Optional) run_name : 

on: # Trigger on the workflow 
  schedule:
    - cron: '0 0/24 * * *' # Execute every 6 hours
  workflow_dispatch: # Allows the workflow to be manually triggered from the GitHub Actions tab.

jobs:
  etl: # Define a job name
    runs-on: windows-latest # Choosing GitHub hosted runners
    # needs: xxx # If requires dependency on other jobs
    steps:
      - name: Access the repo
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.5'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          URI: ${{ secrets.URI }}
        run: python etl_daily.py
      
      - name: Upload data folder
        uses: actions/upload-artifact@v3
        with:
          name: data-files
          path: data/

